### ISSUE TITLE
Maybe.maybe has wrong type (or wrong document)

### ISSUE THREAD

**Issue by Ailrun** [cbowdon/TsMonad#31]
`Maybe.maybe` has `<T>(t: T): Maybe<T>` type,
but its document says

> A Maybe object containing the value passed in input. If t is null
> or undefined, the Maybe object is filled with Nothing.

Therefore, at least I think, right type is `<T>(t?: T): Maybe<T>` or `<T>(t: T | undefined | null): Maybe<T>`.

Is there any problem for these types?

**Comment by cbowdon** [comment]
Good question. At the time this was authored, null and undefined were not separate types in the TS system, so the signature made sense. However I am very much in favour of the new stricter types so will look into updating this.

**Comment by cbowdon** [comment]
Addendum: a PR for this would be welcome.

**Comment by mandrolic** [comment]
FYI, having used as a very similar TS maybe monad, I've found enabling strict null checks changes things quite a bit. The 'auto-null-to-nothing' map() behaviour becomes far less desirable, and less needed because  cases where the projector function returns null are known to the compiler anyway.  It really makes writing a large maybe computation easier, because map() is simply a map(), you know longer have to think about the edge cases where maybe it *won't* be a plain map().

**Comment by cbowdon** [comment]
Cool, thanks for this feedback. Sounds like something I need to get on with checking out.

**Comment by piq9117** [comment]
Hello! I'm a newbie trying to contribute to OSS. Can I make the PR based on @Ailrun suggestion?

**Comment by cbowdon** [comment]
That would be most welcome :)

**Comment by cbowdon** [comment]
Closing this thanks to @piq9117's contribution :)
