### ISSUE TITLE
Type file is missing in 0.8.0

### ISSUE THREAD

**Issue by russelldmatt** [cbowdon/TsMonad#44]
This is likely user error as I'm new to typescript, but I'm having the same issue with 0.8.0.  As a sanity check, I installed 0.7.2, but even with that version I still don't see the tsmonad.d.ts file.  

With latest (0.8.0):
```bash
Matts-MacBook-Pro-3:typescript russell$ npm install tsmonad
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ tsmonad@0.8.0
added 1 package in 0.626s
Matts-MacBook-Pro-3:typescript russell$ tree node_modules/
node_modules/
└── tsmonad
    ├── LICENSE-MIT
    ├── README.md
    ├── dist
    │   ├── tsmonad.js
    │   └── tsmonad.js.map
    ├── lib
    │   └── src
    │       ├── either.d.ts
    │       ├── index.d.ts
    │       ├── maybe.d.ts
    │       ├── monad.d.ts
    │       └── writer.d.ts
    └── package.json

4 directories, 10 files
```

Any help would be appreciated, thanks!

**Comment by cbowdon** [comment]
Possibly related to #35 

You're right, there is no tsmonad.d.ts. I'm afraid it's been literally a year since I used TsMonad myself, so off the top of my head I'm not sure why not. Looking at that tree output I'd guess other users are using the individual definitions under lib/src. Perhaps that would work for you?

**Comment by cbowdon** [comment]
Sorry, I have no time to look into this. Please reopen if it's a concern.
